[workspace]
resolver = "2"
members = ["contracts/trustforge_bond", "contracts/trustforge_delegation", "contracts/trustforge_registry", "contracts/trustforge_treasury", "contracts/timelock", "contracts/trustforge_arbitration", "contracts/trustforge_multisig", "contracts/trustforge_admin", "contracts/trustforge_errors", "contracts/trustforge_math", "contracts/templates", "crates/trustforge_admin_cli", "crates/testutils"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
